### ISSUE TITLE
Platform Agnostic 

### ISSUE THREAD

**Issue by bneiluj** [Ekberjan/FingerprintEnhancement#1]
How can we use the repo to be platform agnostic (through the command line) ? 
I can see it does require Windows platform (`SDKDDKVer.h`).

**Comment by Ekberjan** [comment]
I didn't try it before. Something like cross-platform compilation might help. I'll update if I succeed.

**Comment by bneiluj** [comment]
Well - I'm just trying to run the code on my mac os terminal - but I saw that the project was linked to windows dependencies :/

**Comment by jjerphan** [comment]
Have you managed to do something so that it can be cross-platform compiled? 

I'm on Linux and I've created a makefile to do so (see [my fork](https://github.com/jjerphan/Fingerprint_Image_Enhancement)) but I'm getting a link error:
```
:-1: error : /tmp/cccHIkDr.o: undefined reference to symbol '_ZN2cv6imreadERKNS_6StringEi'
/usr/local/lib/libopencv_imgcodecs.so.3.2:-1: error : error adding symbols: DSO missing from command line
```

**Comment by Ekberjan** [comment]
Seems like you're missing opencv lib on your linux, see [here](https://stackoverflow.com/questions/24096807/dso-missing-from-command-line)

Try to double-check it. I have no problem compiling with gcc under linux.

**Comment by Ekberjan** [comment]
`targetver.h` and `stdafx.h` files are generated under Visual Studio, and the whole code is not dependent on them if you want to compile it under linux or mac. Try to compile without these two hearders if you are not working under VS.

**Comment by jjerphan** [comment]
Yes, it seems like g++ doesn't find OpenCV but I have it installed on my machine. I'll remove the two headers you talk about and try again.

What do you use to compile on Linux ? :)

**Comment by Ekberjan** [comment]
Try to provide `gcc` with library path parameter then (`-L` param), take a look at [here](https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_C_libraries.html) and [here](http://www.rapidtables.com/code/linux/gcc/gcc-l.htm).

**Comment by jjerphan** [comment]
I need some further configuration with OpenCV for my configuration.
I may propose a PR for some improvements of your code. 😄

**Comment by jjerphan** [comment]
Update here ! We have improved your code quite a lot and we are optimizing it so that it can run as fast as possible. Moreover, we think that some functions you've implemented can be replaced with function coming from OpenCV as those latter are optimized.

Here is an example, for this image bellow
![0](https://user-images.githubusercontent.com/13029839/33241623-1a5b3010-d2c0-11e7-99aa-864bb6328927.jpg)

we get this result:
![result0](https://user-images.githubusercontent.com/13029839/33241625-22775f76-d2c0-11e7-98b3-38b0e762fc7a.png)

We look forward your comments! :D

**Comment by Ekberjan** [comment]
I didn't have the chance to run your code, but looks like you did an amazing job! Thanks and well done! Great!

**Comment by jjerphan** [comment]
We did not put it online yet as we are improving it… but thank you! :)

**Comment by jjerphan** [comment]
We finally made [the PR](https://github.com/Ekberjan/Fingerprint_Image_Enhancement/pull/2) we were talking about ! :)

Looking forward to your comments !

**Comment by Ekberjan** [comment]
Thanks so much! I merged it. Good job!
