### ISSUE TITLE
How to use on Windows ?

### ISSUE THREAD

**Issue by MathildeSailly** [Ekberjan/FingerprintEnhancement#13]
How can I use this on Windows ? I have been trying to make it work with Visual Studio 2019, OpenCV 3.2.0 (installed with vc14 found in the official opencv website releases) and I first thought that it was a compatibility problem, but I know believe that it is actually because I am using the wrong command lines.

How can i replace cmake .. and make, for windows ? In the context of this tutorial ?

Thank you

**Comment by Ekberjan** [comment]
Please follow online instructions related to cmake on Windows.

**Comment by MathildeSailly** [comment]
On Windows, when I do the cmake .. (it creates a visual studio file .sln) and then try to open the solution, I have this error : 
![image](https://user-images.githubusercontent.com/71396560/173037006-0f2d4fdd-ddbf-431d-872f-ea21f90214c3.png)
Did you ever have anything similar happenning to you ?
