### ISSUE TITLE
Update license to be less restrictive

### ISSUE THREAD

**Issue by jjerphan** [Ekberjan/FingerprintEnhancement#3]
Hello @Ekberjan, @BaptisteAmato 

I would like to maintain this project (update the code to use a newer version of OpenCV, refactor and improve it, add a build CI, etc.) As of now, the GPL is used for this project. Changing it for BSD (as an example) to be less restrictive might be useful to get more contributions, maintenance and gain adoption.

See this comparison of [free and open-source licenses](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences).

What do you think of it ? 🙂

**Comment by BaptisteAmato** [comment]
Totally up for that!

**Comment by Ekberjan** [comment]
Hi Julien, 
Thanks for your effort, that would be great. And, I accepted your pull request. 
Best.
